---
abstract: 'display information about the current request/response'
author:
  - 'Marcel Grünauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug
no_index:
  directory:
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Class::Method::Modifiers: 1.05
  Data::Dump: 0
  Encode: 2.23
  File::ShareDir: 1.00
  Module::Versions: 0.01
  Plack: 0
  Text::MicroTemplate: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack-Middleware-Debug.git
version: 0.10
