---
abstract: 'display information about the current request/response'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug
no_index:
  directory:
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Class::Method::Modifiers: 1.05
  Data::Dump: 0
  File::ShareDir: 1.00
  Plack: 0
  Text::MicroTemplate: 0
  parent: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Plack-Middleware-Debug
  homepage: http://search.cpan.org/dist/Plack-Middleware-Debug/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/plack-middleware-debug.git
version: 0.03
